In [ ]:
Python
|->Programming Language
     |=> download python from https://www.python.org = CPython - we can do python programming 
                                                       --------
     Python - everything is a class object design model
              ..........
               10 <== is an object - belongs to int class
               'ab' <== is an object - belongs to str class
              10.0 <== floating object - float class
               True /False <== bool class
     containers 
        - list tuple dict set
          ===============

    |-> download python from https://www.anaconda.com/download 
                            ---------------------------------
                we can do python + DataScience + ML modules - available 

In [1]:
print(type(10))

<class 'int'>


In [2]:
i = 10
j = 4+6
k = 2+8
l = 3+7

print(hex(id(i)))
print(hex(id(j)))
print(hex(id(k)))
print(hex(id(l)))

0x7ffe10f3b4c8
0x7ffe10f3b4c8
0x7ffe10f3b4c8
0x7ffe10f3b4c8


In [3]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [ ]:
product
 |-> productID       - 101       = int    => product_id = 101
 |-> productName     - 'pA'      = str    => product_name = 'pA'
 |-> productCost     - 1000.32   = float  => product_cost = 1000.32
 |-> productSales    - True      = bool   => product_Sales = True
Vs
product_info1 = [101,'pA',1000.32,True] <== list - Collection of different types of items - mutable 
                                                 - we can add/modify/delete
Vs
product_info2 = (101,'pA',1000.32,True) <== tuple - Collection of different types of items - immutable
                                                  - we can't add/modify/delete

Vs
product_info3 = {'pid':101,'pname':'pA','pcost':1000.32,'pstatus':True} <== dict
                - Collection of different types of items - mutable
                - - we can add/modify/delete

In [4]:
# Given List 
product_info1 = [101,'pA',1000.32,True]

print(type(product_info1))

<class 'list'>


In [5]:
print(product_info1[0])
print(product_info1[1])
print(product_info1[-1])

101
pA
True


In [6]:
product_info1[2]

1000.32

In [7]:
# To modify
product_info1[2] = 4590.32 

In [8]:
print(product_info1)

[101, 'pA', 4590.32, True]


In [9]:
# tuple - record 
product_info2 = (101,'pA',1000.32,True) # immutable
print(type(product_info2))

<class 'tuple'>


In [10]:
product_info2

(101, 'pA', 1000.32, True)

In [11]:
product_info2[0]

101

In [12]:
product_info2[-1]

True

In [13]:
product_info3 = {'pid':101,'pname':'pA','pcost':1000.32,'pstatus':True}
print(type(product_info3))

<class 'dict'>


In [14]:
product_info3['pid']

101

In [15]:
product_info3['pcost']

1000.32

In [16]:
product_info3['pcost'] = 5689.42 # we can modify an existing value

In [17]:
product_info3

{'pid': 101, 'pname': 'pA', 'pcost': 5689.42, 'pstatus': True}

In [ ]:
list,dict - mutable 

list,dict
...................................
list of list  => [ [],[],[],[] ]
list of dict  => [ {},{},{},{} ] 
dict of list  => { 'key1': [], 'key2':[] ... 'Kn':[] } <=== 
dict of dict  => { 'Key1': {} , 'Key2':{} }
...................................

In [18]:
# list of list
product_list = [[101,'pA',1000],[102,'pB',2000],[103,'pC',3000]]
product_list

[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000]]

In [19]:
product_list.append([104,'pD',3450])
product_list

[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000], [104, 'pD', 3450]]

In [20]:
print(product_list[0])
print(product_list[1])

[101, 'pA', 1000]
[102, 'pB', 2000]


In [21]:
print(product_list[1][0])

102


In [23]:
# list of dict
product_list = [{'pid':101,'pname':'pA','pcost':1000},
                {'pid':102,'pname':'pB','pcost':2000},
                {'pid':103,'pname':'pC','pcost':3000}
               ]

In [24]:
product_list[0]

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [25]:
product_list[0]['pname'] # list of dict

'pA'

In [26]:
L = [["D1","D2","D3"],{"K1":"D4","K2":"D5"}]
L

[['D1', 'D2', 'D3'], {'K1': 'D4', 'K2': 'D5'}]

In [ ]:
# Create a product list - productName,productID,productCost
# -----------------------
# dict of list => d={'Key1':[]}
#
# dict of dict => d={'Key1':{}}

In [27]:
products = {}

products['pid'] = []
products['pname'] = []
products['pcost'] = []
products

{'pid': [], 'pname': [], 'pcost': []}

In [28]:
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1000)
products

{'pid': [101], 'pname': ['pA'], 'pcost': [1000]}

In [29]:
products['pid'].append(102)
products['pname'].append('pB')
products['pcost'].append(2000)
products['pid'].append(103)
products['pname'].append('pC')
products['pcost'].append(3000)

In [30]:
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [31]:
# dict of dict

products={}
products['K1']={'pid':101,'pname':'pA','pcost':1000}
products['K2']={'pid':102,'pname':'pB','pcost':2000}
products['K3']={'pid':103,'pname':'pC','pcost':3000}
products['K4']={'pid':104,'pname':'pD','pcost':4000}
products

{'K1': {'pid': 101, 'pname': 'pA', 'pcost': 1000},
 'K2': {'pid': 102, 'pname': 'pB', 'pcost': 2000},
 'K3': {'pid': 103, 'pname': 'pC', 'pcost': 3000},
 'K4': {'pid': 104, 'pname': 'pD', 'pcost': 4000}}

In [32]:
products['K1']

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [33]:
products['K1']['pname']

'pA'

In [ ]:
[
  {
    "login": "ggobi",
    "id": 423638,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQyMzYzOA==",
    "url": "https://api.github.com/orgs/ggobi",
    "repos_url": "https://api.github.com/orgs/ggobi/repos",
    "events_url": "https://api.github.com/orgs/ggobi/events",
    "hooks_url": "https://api.github.com/orgs/ggobi/hooks",
    "issues_url": "https://api.github.com/orgs/ggobi/issues",
    "members_url": "https://api.github.com/orgs/ggobi/members{/member}",
    "public_members_url": "https://api.github.com/orgs/ggobi/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/423638?v=4",
    "description": ""
  }
]

In [ ]:
numpy   - Computation
  |-> index , slicing , reshaping
  |-> ufunctions 

pandas  - Analysis
  |-> Series
  |-> DataFrame 

matplotlib - Visualization
 |-> plot,scatter,bar,pie,....

In [34]:
L=[10,20,30,40,50]
L+100

TypeError: can only concatenate list (not "int") to list

In [36]:
import numpy
numpy.array([])

array([], dtype=float64)

In [37]:
import numpy as np
np.array([])

array([], dtype=float64)

In [38]:
arr = np.array([10,20,30,40,50])
arr+100

array([110, 120, 130, 140, 150])

In [39]:
arr+100.56

array([110.56, 120.56, 130.56, 140.56, 150.56])

In [41]:
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40 50]
int64
(5,)
1


In [47]:
print(np.array([10,20,30]).dtype)
print(np.array([10,20,30.0]).dtype)
print(np.array([10,20,True]).dtype)
print(np.array([True,False]).dtype)
print(np.array([10,20,3.5,True]).dtype)
print('')
print(np.array([10,20,'data']).dtype)

int64
float64
int64
bool
float64

<U21


In [48]:
np.array([10,20,30])+100

array([110, 120, 130])

In [49]:
np.array([10,20,'data'])+100

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [50]:
np.array([10,20,30]).ndim

1

In [51]:
np.array([[10,20,30]]).ndim

2

In [53]:
arr = np.array([[10,20,30]])
arr.ndim

2

In [55]:
arr

array([[10, 20, 30]])

In [56]:
arr[0]

array([10, 20, 30])

In [57]:
arr[0][0]

np.int64(10)

In [61]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.ndim,arr.shape)
print(arr)

2 (2, 3)
[[10 20 30]
 [40 50 60]]


In [ ]:
      C1  C2   C3  
row1 10 | 20 | 30
     ---|----|--
row2 40 |50  |60

In [62]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [63]:
arr.reshape(1,6)

array([[10, 20, 30, 40, 50, 60]])

In [64]:
arr.reshape(6,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [65]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [66]:
arr.reshape(-1,1) # Convert to 2D

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [ ]:
# numpy universal functions
# ----------------------------
np.mean() => np.mean(data) 
np.median() =>np.median(data) 
np.std() -> np.std(data)
np.max(data)
np.min(data)
np.sum(data) - sum of all items


In [69]:
# Python way - Calculate sum of given list

L=[10,20,30,40,50]

total = 0
for var in L:
    total = total + var
print(total)

## Vs
# numpy 
arr = np.array(L)
print(np.sum(arr))

150
150


In [70]:
np.mean(arr)

np.float64(30.0)

In [71]:
np.median(arr)

np.float64(30.0)

In [72]:
arr = np.array([[1,2,3],[4,5,6]])

print(np.mean(arr))

3.5


In [ ]:
   |  |    |  <== Column = axis=0
--------->--------------
           Row = axis = 1

In [73]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.mean(arr,axis=1) # row

array([2., 5.])

In [75]:
np.mean(arr,axis=0) # column

array([2.5, 3.5, 4.5])

In [77]:
products = {'pid':[],'pname':[],'pcost':[]}
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1000)
products

{'pid': [101], 'pname': ['pA'], 'pcost': [1000]}

In [78]:
products['pid'].append(102)
products['pname'].append('pB')
products['pcost'].append(2000)
products['pid'].append(103)
products['pname'].append('pC')
products['pcost'].append(3000)
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

In [79]:
products

{'pid': [101, 102, 103, 104],
 'pname': ['pA', 'pB', 'pC', 'pD'],
 'pcost': [1000, 2000, 3000, 4000]}

In [80]:
print(type(products))

<class 'dict'>


In [81]:
products['pcost']

[1000, 2000, 3000, 4000]

In [82]:
arr = np.array(products['pcost']) # ->numpy_array_object
np.sum(arr)

np.int64(10000)

In [83]:
np.max(arr)

np.int64(4000)

In [84]:
np.mean(arr)

np.float64(2500.0)

In [ ]:
###################################################

In [85]:
import pandas
pandas

<module 'pandas' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>

In [88]:
print(pandas.Series)

<class 'pandas.core.series.Series'>


In [89]:
print(pandas.DataFrame)

<class 'pandas.core.frame.DataFrame'>


In [ ]:
pandas/
   |___core/
        |__frame.py
               |__class DataFrame:

In [91]:
import pandas as pd
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [92]:
pd.DataFrame([10,20,30,40,50])

0
0  10
1  20
2  30
3  40
4  50

In [93]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [94]:
pd.DataFrame(products)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [95]:
df1 = pd.DataFrame(products)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     3 non-null      int64 
 1   pname   3 non-null      object
 2   pcost   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


In [96]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [97]:
df1.columns

Index(['pid', 'pname', 'pcost'], dtype='object')

In [ ]:
# To fetch data - row based => df.loc[index] -> record 
#
# To fetch data - column based -> df['ColumnName'] -> column
#                                 -like dictName['key']

In [98]:
df1.loc[1]

pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [99]:
df1.loc[0]

pid       101
pname      pA
pcost    1000
Name: 0, dtype: object

In [101]:
df1.loc[1]

pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [102]:
df1['pid']

0    101
1    102
2    103
Name: pid, dtype: int64

In [103]:
df1['pname']

0    pA
1    pB
2    pC
Name: pname, dtype: object

In [104]:
df1.loc[1]['pname']

'pB'

In [ ]:
# add more products to product_structure(dict) - do append operation
# |->initialize to DataFrame ->new_df 
#                                 |->Fetch Row X Column 

In [105]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]


In [106]:
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

products['pid'].append(105)
products['pname'].append('pE')
products['pcost'].append(5000)

products['pid'].append(106)
products['pname'].append('pF')
products['pcost'].append(6000)

products['pid'].append(107)
products['pname'].append('pG')
products['pcost'].append(2300)

products['pid'].append(108)
products['pname'].append('pH')
products['pcost'].append(3400)

In [108]:
df2 = pd.DataFrame(products)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     8 non-null      int64 
 1   pname   8 non-null      object
 2   pcost   8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes


In [109]:
df2['pid']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
Name: pid, dtype: int64

In [110]:
df2.loc[2]

pid       103
pname      pC
pcost    3000
Name: 2, dtype: object

In [111]:
df2.loc[2:] # from 2nd row to list of all - Slicing

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [112]:
df2.loc[2:5] # from 2nd row - 5th row

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000

In [113]:
df2.loc[3]['pname']

'pD'

In [115]:
df2.loc[3][['pname','pcost']]

pname      pD
pcost    4000
Name: 3, dtype: object

In [118]:
df2.loc[2:5][['pname','pcost']] # from 2nd row - 5th row - filter productName,productCost

pname  pcost
2    pC   3000
3    pD   4000
4    pE   5000
5    pF   6000

In [121]:
df2['pcost']
df2['pcost'] * 0.18

0     180.0
1     360.0
2     540.0
3     720.0
4     900.0
5    1080.0
6     414.0
7     612.0
Name: pcost, dtype: float64

In [122]:
df2['pcost'] >3000

0    False
1    False
2    False
3     True
4     True
5     True
6    False
7     True
Name: pcost, dtype: bool

In [123]:
df2[df2['pcost'] >3000] # boolean index - filter True values/records only

pid pname  pcost
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
7  108    pH   3400

In [ ]:
# In pandas DataFrame - mutable - inplace=True <== modified input DataFrame

In [124]:
# To delete a particular row/record 
# df.drop(rowIndex)
len(df2.index)

8

In [125]:
df2.drop(3) # delete 3rd row

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [126]:
len(df2.index)

8

In [127]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [128]:
df3 = df2.drop(3)
print(len(df3.index))
print(len(df2.index))

7
8


In [129]:
df2.drop(4,inplace=True) # ->None. But dataframe is updated

In [130]:
len(df2.index)

7

In [131]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [ ]:
######## 

In [132]:
# To drop Columns
# -----------------
# df.drop(columns='SingleColumn') Vs df.drop(columns=['Col1','Col2','Col3'])
# ===============================    ========================================
#
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [133]:
df2.drop(columns='pname')

pid  pcost
0  101   1000
1  102   2000
2  103   3000
3  104   4000
5  106   6000
6  107   2300
7  108   3400

In [134]:
df2.drop(columns=['pid','pname'])

pcost
0   1000
1   2000
2   3000
3   4000
5   6000
6   2300
7   3400

In [135]:
d={'K1':[10,20,30,40],'K2':['d1','d2','d3','d4'],'K3':['V1','V2','V3','V4'],'K4':[1.2,2.3,3.2,4.3]}
d

{'K1': [10, 20, 30, 40],
 'K2': ['d1', 'd2', 'd3', 'd4'],
 'K3': ['V1', 'V2', 'V3', 'V4'],
 'K4': [1.2, 2.3, 3.2, 4.3]}

In [136]:
pd.DataFrame(d)

K1  K2  K3   K4
0  10  d1  V1  1.2
1  20  d2  V2  2.3
2  30  d3  V3  3.2
3  40  d4  V4  4.3

In [137]:
new_df = pd.DataFrame(d)
new_df.drop(columns=['K1','K3'],inplace=True)

In [138]:
new_df

K2   K4
0  d1  1.2
1  d2  2.3
2  d3  3.2
3  d4  4.3

In [139]:
## rename columns
# ----------------------
# df.rename(columns = {'oldColumnName':'newColumn'})
#                      =========================
new_df

K2   K4
0  d1  1.2
1  d2  2.3
2  d3  3.2
3  d4  4.3

In [140]:
new_df.rename(columns={'K2':'Field2'})

Field2   K4
0     d1  1.2
1     d2  2.3
2     d3  3.2
3     d4  4.3

In [141]:
new_df

K2   K4
0  d1  1.2
1  d2  2.3
2  d3  3.2
3  d4  4.3

In [142]:
new_df.rename(columns={'K2':'Field2'},inplace=True)
new_df

Field2   K4
0     d1  1.2
1     d2  2.3
2     d3  3.2
3     d4  4.3

In [143]:
d={}
d['K1']=[10,20,None]
d['K2']=[15,None,None]
d['K3']=[None,11,None]
pd.DataFrame(d)

K1    K2    K3
0  10.0  15.0   NaN
1  20.0   NaN  11.0
2   NaN   NaN   NaN

In [144]:
df3 = pd.DataFrame(d)
df3.isnull()

K1     K2     K3
0  False  False   True
1  False   True  False
2   True   True   True

In [145]:
df3.isnull().sum()

K1    1
K2    2
K3    2
dtype: int64

In [146]:
# To replace NaN Value => fillna(<replacementValue>)
#
df3.fillna('testdata')

K1        K2        K3
0      10.0      15.0  testdata
1      20.0  testdata      11.0
2  testdata  testdata  testdata

In [147]:
df3.fillna(55)

K1    K2    K3
0  10.0  15.0  55.0
1  20.0  55.0  11.0
2  55.0  55.0  55.0

In [149]:
df3['K1'].fillna(54)

0    10.0
1    20.0
2    54.0
Name: K1, dtype: float64

In [150]:
df3[['K2','K3']].fillna(65.21)

K2     K3
0  15.00  65.21
1  65.21  11.00
2  65.21  65.21

In [151]:
df3

K1    K2    K3
0  10.0  15.0   NaN
1  20.0   NaN  11.0
2   NaN   NaN   NaN

In [154]:
df3.fillna(65.21,inplace=True)

In [155]:
df3

K1     K2     K3
0  10.00  15.00  65.21
1  20.00  65.21  11.00
2  65.21  65.21  65.21

In [156]:
df3.isnull().sum()

K1    0
K2    0
K3    0
dtype: int64

In [157]:
df3.duplicated()

0    False
1    False
2    False
dtype: bool

In [158]:
df3.duplicated().sum()

np.int64(0)

In [160]:
d={'K1':[10,10,30],'K2':[10,10,30],'K3':[10,10,30]}
df4 = pd.DataFrame(d)
df4

K1  K2  K3
0  10  10  10
1  10  10  10
2  30  30  30

In [161]:
df4.duplicated().sum()

np.int64(1)

In [162]:
df4.drop_duplicates()

K1  K2  K3
0  10  10  10
2  30  30  30

In [163]:
df4.drop_duplicates(inplace=True)

In [164]:
df4

K1  K2  K3
0  10  10  10
2  30  30  30

In [166]:
d={'K1':[10,20,30],'K2':[15,None,None],'K3':[45,15,None],'K4':[11,12,13]}
df5 = pd.DataFrame(d)
print(df5)
df5.dropna()

   K1    K2    K3  K4
0  10  15.0  45.0  11
1  20   NaN  15.0  12
2  30   NaN   NaN  13


K1    K2    K3  K4
0  10  15.0  45.0  11

In [167]:
df5.dropna(axis=1) # drop column

K1  K4
0  10  11
1  20  12
2  30  13

In [168]:
# How to modify an existing nth data in dataframe
#
# df.at[rowIndex,ColumnName] = updatedValue
# ===========================================

df5

K1    K2    K3  K4
0  10  15.0  45.0  11
1  20   NaN  15.0  12
2  30   NaN   NaN  13

In [170]:
print(df5.loc[0]['K2'])
df5.at[0,'K2'] = 4590.23 # we can modify an existing nth data
df5

15.0


K1       K2    K3  K4
0  10  4590.23  45.0  11
1  20      NaN  15.0  12
2  30      NaN   NaN  13

In [178]:
# Delete based on keyword -case sensitive 
df = pd.DataFrame({'K1':['Data1','Value2','Data3'],
                   'K2':['ab@example.com','xy@Example.com','dd@example.com']})

print(df)
df.drop(index=1)

       K1              K2
0   Data1  ab@example.com
1  Value2  xy@Example.com
2   Data3  dd@example.com


K1              K2
0  Data1  ab@example.com
2  Data3  dd@example.com

In [179]:
print(df)
df = df[~df['K1'].str.contains('data',case=False)]
df

       K1              K2
0   Data1  ab@example.com
1  Value2  xy@Example.com
2   Data3  dd@example.com


K1              K2
1  Value2  xy@Example.com

In [ ]:
###########

In [180]:
df=pd.DataFrame({'K1':[10,20,30],'K2':[12,13,34],'K3':['D1','D2','D3']})

K1  K2  K3
0  10  12  D1
1  20  13  D2
2  30  34  D3

In [181]:
pd.read_csv('emp.csv') #  Vs pd.DataFrame({'Key1':[],'Key2':[]})

eid    ename  edept    ecity  ecost
0  101      raj  sales     pune   1000
1  102      leo   prod   bglore   2301
2  230      raj   prod     pune   2300
3  450     shan  sales   bglore   3401
4  542      anu     HR   mumbai   4590
5  321     bibu  sales      hyd   5419
6  651      ram     hr   bglore   3130
7  541      leo  admin  chennai   4913
8  652  karthik  sales   bglore   3405

In [182]:
df=pd.DataFrame({'K1':[10,20,30],'K2':[12,13,34],'K3':['D1','D2','D3']})
df.to_csv('t1.csv')

In [183]:
df

K1  K2  K3
0  10  12  D1
1  20  13  D2
2  30  34  D3

In [185]:
pd.read_csv('t1.csv')

Unnamed: 0  K1  K2  K3
0           0  10  12  D1
1           1  20  13  D2
2           2  30  34  D3

In [186]:
df.to_csv('t2.csv',index=False)

In [187]:
pd.read_csv('t2.csv')

K1  K2  K3
0  10  12  D1
1  20  13  D2
2  30  34  D3

In [ ]:
# Tasks
# ----------
# 1. load emp.csv file content to pandas  -> df
# 2. get info about loaded DataFrame
# 3. List out row index , column index
# 4. display df shape
# 5. Test - any duplicated values are exists -> drop duplicated updated to input dataframe
# 6. Test - any NaN value is exists => drop NaN index based and Column based
# 7. Test - any NaN ->replace row/column 
# 8. Rename some selective columns - modified input data frame(ex: edept =>DEPT 'ecost' ->Amount)
# 9. Drop some selective columns
# 10. Write DataFrame to External File
----------------------------------------------------------------

In [188]:
# 1. load emp.csv file content to pandas  -> df

df_csv = pd.read_csv('emp.csv')


# 2. get info about loaded DataFrame
df_csv.info()

# 3. List out row index , column index
print('Row index:',df_csv.index)
print('List of columns:',df_csv.columns)

# 4. Display shape of the data - Row X Col
print(df_csv.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   eid     9 non-null      int64 
 1   ename   9 non-null      object
 2   edept   9 non-null      object
 3   ecity   9 non-null      object
 4   ecost   9 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes
Row index: RangeIndex(start=0, stop=9, step=1)
List of columns: Index(['eid', 'ename', 'edept', 'ecity', 'ecost'], dtype='object')
(9, 5)


In [191]:
# # 5. Test - any duplicated values are exists -> drop duplicated updated to input dataframe
df_csv.duplicated()
df_csv.duplicated().sum()
df_csv.drop_duplicates(inplace=True)

In [192]:
# 6. Test - any NaN value is exists => drop NaN index based and Column based
df_csv.isnull().sum()

# 7. Test - any NaN ->replace row/column 
df_csv.dropna() # default rowbased 
df_csv.dropna(axis=1) # columnbased 
df_csv.fillna('sampledata') # replace NaN ->sampledata
df_csv['edept'].fillna('commonDept')

eid      0
ename    0
edept    0
ecity    0
ecost    0
dtype: int64

In [194]:
# 8. Rename some selective columns - modified input data frame(ex: edept =>DEPT 'ecost' ->Amount)
print(df_csv.columns)
df_csv.rename(columns={'edept':'DEPT','ecost':'Amount'},inplace=True)
print(df_csv.columns)

Index(['eid', 'ename', 'edept', 'ecity', 'ecost'], dtype='object')
Index(['eid', 'ename', 'DEPT', 'ecity', 'Amount'], dtype='object')


In [195]:
# 9. Drop some selective columns
df_csv.drop(columns=['eid','ecity'])

ename   DEPT  Amount
0      raj  sales    1000
1      leo   prod    2301
2      raj   prod    2300
3     shan  sales    3401
4      anu     HR    4590
5     bibu  sales    5419
6      ram     hr    3130
7      leo  admin    4913
8  karthik  sales    3405

In [196]:
df_csv.drop(columns=['eid','ecity'],inplace=True)

In [197]:
df_csv.columns

Index(['ename', 'DEPT', 'Amount'], dtype='object')

In [198]:
# 10. Write DataFrame to External File
df_csv.to_csv('r1.csv',index=False)

In [199]:
pd.read_csv('r1.csv')

ename   DEPT  Amount
0      raj  sales    1000
1      leo   prod    2301
2      raj   prod    2300
3     shan  sales    3401
4      anu     HR    4590
5     bibu  sales    5419
6      ram     hr    3130
7      leo  admin    4913
8  karthik  sales    3405

In [200]:
len(df_csv)

9

In [202]:
for var in range(1,len(df_csv.index)+1):
    print(var,end=' ')

1 2 3 4 5 6 7 8 9 

In [203]:
[var for var in range(1,len(df_csv.index)+1)]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [204]:
df_csv.index = [var for var in range(1,len(df_csv.index)+1)]

In [205]:
df_csv.index

Index([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [206]:
df_csv

ename   DEPT  Amount
1      raj  sales    1000
2      leo   prod    2301
3      raj   prod    2300
4     shan  sales    3401
5      anu     HR    4590
6     bibu  sales    5419
7      ram     hr    3130
8      leo  admin    4913
9  karthik  sales    3405

In [ ]:
################################################

In [207]:
df_csv.sort_index()

ename   DEPT  Amount
1      raj  sales    1000
2      leo   prod    2301
3      raj   prod    2300
4     shan  sales    3401
5      anu     HR    4590
6     bibu  sales    5419
7      ram     hr    3130
8      leo  admin    4913
9  karthik  sales    3405

In [208]:
df_csv.sort_index(ascending=False)

ename   DEPT  Amount
9  karthik  sales    3405
8      leo  admin    4913
7      ram     hr    3130
6     bibu  sales    5419
5      anu     HR    4590
4     shan  sales    3401
3      raj   prod    2300
2      leo   prod    2301
1      raj  sales    1000

In [209]:
df_csv.sort_values(by='ename') # sort emp names in ascending order

ename   DEPT  Amount
5      anu     HR    4590
6     bibu  sales    5419
9  karthik  sales    3405
2      leo   prod    2301
8      leo  admin    4913
1      raj  sales    1000
3      raj   prod    2300
7      ram     hr    3130
4     shan  sales    3401

In [210]:
df_csv.sort_values(by='ename',ascending=False) # sort emp names in descending order

ename   DEPT  Amount
4     shan  sales    3401
7      ram     hr    3130
1      raj  sales    1000
3      raj   prod    2300
2      leo   prod    2301
8      leo  admin    4913
9  karthik  sales    3405
6     bibu  sales    5419
5      anu     HR    4590

In [211]:
pd.read_csv('emp.csv',index_col=0)

ename  edept    ecity  ecost
eid                                
101      raj  sales     pune   1000
102      leo   prod   bglore   2301
230      raj   prod     pune   2300
450     shan  sales   bglore   3401
542      anu     HR   mumbai   4590
321     bibu  sales      hyd   5419
651      ram     hr   bglore   3130
541      leo  admin  chennai   4913
652  karthik  sales   bglore   3405

In [212]:
pd.read_csv('emp.csv',index_col=2)

eid    ename    ecity  ecost
edept                              
sales  101      raj     pune   1000
prod   102      leo   bglore   2301
prod   230      raj     pune   2300
sales  450     shan   bglore   3401
HR     542      anu   mumbai   4590
sales  321     bibu      hyd   5419
hr     651      ram   bglore   3130
admin  541      leo  chennai   4913
sales  652  karthik   bglore   3405

In [213]:
df7 = pd.read_csv('emp.csv',index_col=2)
df7.index

Index(['sales', 'prod', 'prod', 'sales', 'HR', 'sales', 'hr', 'admin',
       'sales'],
      dtype='object', name='edept')

In [214]:
df7.columns

Index(['eid', 'ename', 'ecity', 'ecost'], dtype='object')

In [215]:
df7.loc['sales']

eid    ename   ecity  ecost
edept                             
sales  101      raj    pune   1000
sales  450     shan  bglore   3401
sales  321     bibu     hyd   5419
sales  652  karthik  bglore   3405

In [ ]:
Data Aggregation
==================
range of data //array ------>--- scalar data(single)
[1,234,33,4424,234322,43] --->--- max value ? min value ? mean value ? 
                                  ---------------------------------------//Single
np.max()
np.min()
np.mean()
np.sum()
..
df.groupby('field').sum()|max()|min()....

In [216]:
products = {'pname':['pA','pB','pC','pD','pA','pB','pA'],
            'sales':[100,200,300,140,110,120,340]}

df = pd.DataFrame(products)
df.groupby('pname').sum()

sales
pname       
pA       550
pB       320
pC       300
pD       140

In [217]:
df.groupby('pname').min()

sales
pname       
pA       100
pB       120
pC       300
pD       140

In [218]:
df.groupby('pname').max()

sales
pname       
pA       340
pB       200
pC       300
pD       140

In [219]:
df.groupby('pname').agg(['min','max'])

sales     
        min  max
pname           
pA      100  340
pB      120  200
pC      300  300
pD      140  140

In [220]:
df_csv

ename   DEPT  Amount
1      raj  sales    1000
2      leo   prod    2301
3      raj   prod    2300
4     shan  sales    3401
5      anu     HR    4590
6     bibu  sales    5419
7      ram     hr    3130
8      leo  admin    4913
9  karthik  sales    3405

In [221]:
df_csv.to_csv('r1.csv')
df_csv.to_csv('r1.log')

In [222]:
pd.read_csv('r1.log')

Unnamed: 0    ename   DEPT  Amount
0           1      raj  sales    1000
1           2      leo   prod    2301
2           3      raj   prod    2300
3           4     shan  sales    3401
4           5      anu     HR    4590
5           6     bibu  sales    5419
6           7      ram     hr    3130
7           8      leo  admin    4913
8           9  karthik  sales    3405

In [223]:
df_csv.to_csv('r1.log',sep=':')

In [224]:
pd.read_csv('r1.log')

:ename:DEPT:Amount
0      1:raj:sales:1000
1       2:leo:prod:2301
2       3:raj:prod:2300
3     4:shan:sales:3401
4         5:anu:HR:4590
5     6:bibu:sales:5419
6         7:ram:hr:3130
7      8:leo:admin:4913
8  9:karthik:sales:3405

In [226]:
pd.read_csv('r1.log',sep=':')

Unnamed: 0    ename   DEPT  Amount
0           1      raj  sales    1000
1           2      leo   prod    2301
2           3      raj   prod    2300
3           4     shan  sales    3401
4           5      anu     HR    4590
5           6     bibu  sales    5419
6           7      ram     hr    3130
7           8      leo  admin    4913
8           9  karthik  sales    3405

In [ ]:
pd.read_excel('inputFile.xlsx')
pd.read_excel('inputFile.xlsx',sheet_name='Sheet1')

In [ ]:
Python     <---------------DBModule------------------>  DataBase 
DS                                                          SQL
'insert into ... values ..' //str
'select *from table' //str --------------------------------> sql> select ... ->records
                                                                                 |
    ----------------<------------------------------------------------------------|
                [] () [(),(),()]

In [227]:
import sqlite3

In [228]:
conn = sqlite3.connect('test1.db')
sth = conn.cursor()
sth.execute('create table pn(id INT,pname Text,pcost REAL)')

In [229]:
sth.execute("insert into pn(id,pname,pcost) values(101,'pA',1000)")
va = 102
vb = 'pB'
vc = 2000
sth.execute("insert into pn(id,pname,pcost) values(?,?,?)",(va,vb,vc))

In [230]:
sth.execute("insert into pn(id,pname,pcost) values(103,'pC',3000)")
sth.execute("insert into pn(id,pname,pcost) values(104,'pD',4000)")

In [231]:
sth.execute("select *from pn")

In [232]:
sth.fetchone()

(101, 'pA', 1000.0)

In [233]:
sth.fetchone()

(102, 'pB', 2000.0)

In [234]:
sth.fetchone()

(103, 'pC', 3000.0)

In [235]:
sth.fetchone()

(104, 'pD', 4000.0)

In [236]:
sth.fetchone()

In [237]:
sth.execute("select *from pn")
sth.fetchall()

[(101, 'pA', 1000.0),
 (102, 'pB', 2000.0),
 (103, 'pC', 3000.0),
 (104, 'pD', 4000.0)]

In [238]:
sth.execute("select *from pn")
list(sth) # typecast to list - generator logic 

[(101, 'pA', 1000.0),
 (102, 'pB', 2000.0),
 (103, 'pC', 3000.0),
 (104, 'pD', 4000.0)]

In [239]:
conn.commit()

In [240]:
conn.close()

In [241]:
conn = sqlite3.connect('test1.db')
sth = conn.cursor()
sth.execute("select *from pn")
list(sth) # generator 

[(101, 'pA', 1000.0),
 (102, 'pB', 2000.0),
 (103, 'pC', 3000.0),
 (104, 'pD', 4000.0)]

In [242]:
import sqlite3
conn = sqlite3.connect('test1.db')
pd.read_sql_query('select *from pn',conn)

id pname   pcost
0  101    pA  1000.0
1  102    pB  2000.0
2  103    pC  3000.0
3  104    pD  4000.0

In [ ]:
pd.DataFrame({key:[]}) ->df
pd.read_csv('inputFile') ->df
pd.read_sql_query('select query statement',connection_obj) ->df


In [243]:
df_sql = pd.read_sql_query('select *from pn',conn)
df_sql.to_csv('r2.csv',index=False)

In [244]:
pd.read_csv('r2.csv')

id pname   pcost
0  101    pA  1000.0
1  102    pB  2000.0
2  103    pC  3000.0
3  104    pD  4000.0

In [ ]:
Extract - Transformed - Load (ETL)
====================================
Data - Extracted from DataSource(File,API,DB...) -->Transformed(Clean,Aggregated) ->Load
Loaded to the target (Datawarehouse)

Extract-Load-Transformed (ELT)
=================================
Data - Extracted from DataSource(File,API,DB...) ->Loaded first into target system 
->transformed inside the target


In [246]:
#help(df_sql.to_sql)

In [247]:
def fx(a1,a2):
    return a1+a2
fx(10,20)

30

In [248]:
# lambda syntax
# lambda list of args:operation

fy = lambda a1,a2:a1+a2
fy(10,20)

30

In [253]:
df = pd.DataFrame({'name':['A','B','C'],'cost':[1000,2000,3000]})

# df.apply(functionName)
df['Tax'] = df['cost'].apply(lambda a:a*0.12)
df

name  cost    Tax
0    A  1000  120.0
1    B  2000  240.0
2    C  3000  360.0

In [ ]:
# Extract ->Transform -->Load 
# ------------------------------
# products.csv 
# read the products.csv file - Extract
#  with.respect to product cost - apply tax value # Transfor
# Load - create a new database file 
# df.to_sql 

In [258]:
def f1(a1):
    return a1+100
f1(10) # 110

f2 = lambda a:a+100
f2(10) # 110
#########################################################
L=[]
for var in range(1,6):
    if(var >3):
        r = var+100
        L.append(r)
    else:
        r = var+500
        L.append(r)
L

[501, 502, 503, 104, 105]

In [259]:
[var+100 if var >3 else var+500 for var in range(1,6)]

[501, 502, 503, 104, 105]

In [260]:
# Extract
df_prod = pd.read_csv('product.csv')
df_prod.info()
print(df_prod)
print('')

# Transform
df_prod['pcost'] = df_prod.apply(lambda a: a['pcost'] * 12.0 if a['pname'] == 'pC' else a['pcost'],axis=1)
df_prod['pcost']

# Load 
con = sqlite3.connect("product_etl1.db")
df_prod.to_sql('product',con,if_exists='replace',index=False) # loaded to DB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     3 non-null      int64 
 1   pname   3 non-null      object
 2   pcost   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
   pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000



3

In [261]:
# Testing
list(con.execute('select * from product')) # apply generator technique

[(101, 'pA', 1000.0), (102, 'pB', 2000.0), (103, 'pC', 36000.0)]

In [262]:
for var in con.execute('select *from product'): # another way to fetch data from DB ->python
    print(var)

(101, 'pA', 1000.0)
(102, 'pB', 2000.0)
(103, 'pC', 36000.0)


In [ ]:
## ELT
# 1. Extract product.csv data 
# 2. Load same product.csv (raw data) ->DB
# 3. Transform - use SQL query ...

In [264]:
# Extract
df_prod = pd.read_csv('product.csv')
df_prod

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [265]:
# Load - load raw data 
conn = sqlite3.connect('product1.db')
df_prod.to_sql('product_raw',conn,if_exists='replace',index=False)

3

In [267]:
# Transform(inside the db) - inside the DB Via SQL not using python programming 
conn.execute("""create table product_final as 
                SELECT pid,
                      pname,
                      pcost, 
                      CASE 
                        when pname == 'pC' THEN pcost * 18
                      ELSE pcost 
                   END AS pcost
                  FROM product_raw;
                """)
conn.commit()

In [268]:
# Testing
for var in conn.execute("select *from product_final"):
    print(var)

(101, 'pA', 1000, 1000)
(102, 'pB', 2000, 2000)
(103, 'pC', 3000, 54000)


In [ ]:
######################################################

In [ ]:
JSON
 |->Stores  and exchange data - between web applications
list <----->array
dict <----->object

In [271]:
import json

d={'K1':[10,20,30,40],'K2':['URL1','URL2','URL3'],'K3':[True,False]}

print(json.dumps(d,indent=2)) # python ->json

{
  "K1": [
    10,
    20,
    30,
    40
  ],
  "K2": [
    "URL1",
    "URL2",
    "URL3"
  ],
  "K3": [
    true,
    false
  ]
}


In [272]:
json_data = json.dumps(d,indent=2)
json.loads(json_data) # from json to python

{'K1': [10, 20, 30, 40], 'K2': ['URL1', 'URL2', 'URL3'], 'K3': [True, False]}

In [275]:
d={'K1':[10,20,30,40],'K2':['URL1','URL2','URL3','URL4'],'K3':[True,False,"OK","Good"]}
df = pd.DataFrame(d)
df.to_json('product.json',indent=4)

In [276]:
pd.read_json('product.json')

K1    K2     K3
0  10  URL1   True
1  20  URL2  False
2  30  URL3     OK
3  40  URL4   Good

In [ ]:
################

In [ ]:
C:\Users\karth>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> d={'K1':[{'K1':['D1','D2']},{'K2':['Dx','Dy']}]}
>>>
>>> import json
>>>
>>> json.dumps(d)
'{"K1": [{"K1": ["D1", "D2"]}, {"K2": ["Dx", "Dy"]}]}'
>>>
>>> print(json.dumps(d))
{"K1": [{"K1": ["D1", "D2"]}, {"K2": ["Dx", "Dy"]}]}
>>>
>>> print(json.dumps(d,indent=2))
{
  "K1": [
    {
      "K1": [
        "D1",
        "D2"
      ]
    },
    {
      "K2": [
        "Dx",
        "Dy"
      ]
    }
  ]
}
>>> print(json.dumps(d,indent=3))
{
   "K1": [
      {
         "K1": [
            "D1",
            "D2"
         ]
      },
      {
         "K2": [
            "Dx",
            "Dy"
         ]
      }
   ]
}
>>> print(json.dumps(d,indent=5))
{
     "K1": [
          {
               "K1": [
                    "D1",
                    "D2"
               ]
          },
          {
               "K2": [
                    "Dx",
                    "Dy"
               ]
          }
     ]
}
>>> print(json.dumps(d,indent=6))
{
      "K1": [
            {
                  "K1": [
                        "D1",
                        "D2"
                  ]
            },
            {
                  "K2": [
                        "Dx",
                        "Dy"
                  ]
            }
      ]
}
>>>

In [ ]:
################ End of the Session ############################